name: Automated browser tests
on: push
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@master

      - name: Install deps
        run: yarn

      - name: Run tests
        run: yarn test:integration
